CREATE TABLE users(
	ID INT NOT NULL AUTO_INCREMENT,
	MAIL VARCHAR(30) NOT NULL,
	PASS VARCHAR(30) NOT NULL,
	PROFILE VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE users ADD CONSTRAINT UNIQUE(MAIL);

CREATE TABLE time_record(
	ID INT NOT NULL AUTO_INCREMENT,
	DATA DATE NOT NULL,
	TIME_IN TIME NOT NULL,
	TIME_OUT TIME NOT NULL,
	ID_USER INT NOT NULL,
	MOTIVE VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_USER) REFERENCES users(ID) ON DELETE CASCADE
);