CREATE TABLE users(
	ID INT NOT NULL AUTO_INCREMENT,
	MAIL VARCHAR(30) NOT NULL,
	PASS VARCHAR(30) NOT NULL,
	PROFILE VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE users ADD CONSTRAINT UNIQUE(MAIL);
